### PR TITLE
Update classes included in ts-tinkerpop

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz ts-tinkerpop now includes most of the packages that the gremlin groovy console automatically imports, with the notable exception of the driver packages.

The size of the generated java.d.ts file grew by about 4x, from just over 10K lines to just under 40K lines.

### CODE REVIEW

**Comment by mhfrantz** [comment]
LGTM ... add README?

**Comment by jimlloyd** [comment]
PTAL

**Comment by jimlloyd** [comment]
Merging now. Any feedback on README can be incorporated in subsequent PR.

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
