### PR TITLE
[Delivers #98862652 ] Update ts-tinkerpop to use ts-java v1.2.1

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz

### CODE REVIEW

**Comment by mhfrantz** [comment]
In the v10 Makefile, I had to make a change to the way explicit dependencies are declared.  If you have a `lib/foo.js` rule, then you need to include the `*.js.map` file.  This shows up in parallel builds where it will try to compile foo.ts before ts-java has finished.
```
lib/foo.js lib/foo.js.map : $(JAVA_D_TS)
```

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
Good catch. PTAL.

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
