### PR TITLE
Update to tinkerpop 3.0.0.M9

### PR DESCRIPTION
**Pull request by jimlloyd**
@mhfrantz This updates to 3.0.0.M9, by way of an intermediate attempt to update to 3.0.0.M9-rc3.
It's possible we could squash out some of the intermediates, let me know if you'd prefer that.

### CODE REVIEW

**Comment by mhfrantz** [comment]
FTP

I just followed up on a few of the things that I had pointed out previously which still need to be addressed.

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
FTP

**Comment by jimlloyd** [comment]
PTAL

**Comment by mhfrantz** [comment]
LGTM

**Pull request merged**
